{
 "title": "PSQLPY STRESS TEST",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "tag_key", "query": "psqlpy, asyncpg, psycopg" }
  ]
 },
 "panels": [
  {
   "title": "PERCENTILE /  99",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "stress-test-timings-tag::tag" ], "type": "tag" }
     ],
     "measurement": "stress-test-timings",
     "query": "SELECT percentile(\"time-took\", 99) FROM \"stress-test-timings\" WHERE (\"stress-test-timings-tag\"::tag = '$tag_key') AND $timeFilter GROUP BY \"stress-test-timings-tag\"::tag",
     "select": [
      [
       { "params": [ "time-took" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "stress-test-timings-tag::tag", "operator": "=~", "value": "/^$tag_key$/" }
     ]
    }
   ]
  },
  {
   "title": "PERCENTILE /  95",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "stress-test-timings-tag::tag" ], "type": "tag" }
     ],
     "measurement": "stress-test-timings",
     "query": "SELECT percentile(\"time-took\", 95) FROM \"stress-test-timings\" WHERE (\"stress-test-timings-tag\"::tag = '$tag_key') AND $timeFilter GROUP BY \"stress-test-timings-tag\"::tag",
     "select": [
      [
       { "params": [ "time-took" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "stress-test-timings-tag::tag", "operator": "=~", "value": "/^$tag_key$/" }
     ]
    }
   ]
  },
  {
   "title": "PERCENTILE /  90",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "stress-test-timings-tag::tag" ], "type": "tag" }
     ],
     "measurement": "stress-test-timings",
     "query": "SELECT percentile(\"time-took\", 90) FROM \"stress-test-timings\" WHERE (\"stress-test-timings-tag\"::tag = '$tag_key') AND $timeFilter GROUP BY \"stress-test-timings-tag\"::tag",
     "select": [
      [
       { "params": [ "time-took" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ],
     "tags": [
      { "key": "stress-test-timings-tag::tag", "operator": "=~", "value": "/^$tag_key$/" }
     ]
    }
   ]
  },
  {
   "title": "RPS / 10s",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "stress-test-timings-tag::tag" ], "type": "tag" }
     ],
     "measurement": "stress-test-timings",
     "query": "SELECT count(\"time-took\") FROM \"stress-test-timings\" WHERE (\"stress-test-timings-tag\"::tag = '$tag_key') AND $timeFilter GROUP BY time(10s), \"stress-test-timings-tag\"::tag",
     "select": [
      [
       { "params": [ "time-took" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "condition": "OR", "key": "stress-test-timings-tag::tag", "operator": "=", "value": "psqlpy" }
     ]
    }
   ]
  },
  {
   "title": "TOTAL REQUESTS / 10s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "stress-test-timings-tag::tag" ], "type": "tag" }
     ],
     "measurement": "stress-test-timings",
     "query": "SELECT count(\"time-took\") FROM \"stress-test-timings\" WHERE (\"stress-test-timings-tag\"::tag = '$tag_key') AND $timeFilter GROUP BY time(10s), \"stress-test-timings-tag\"::tag",
     "select": [
      [
       { "params": [ "time-took" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "stress-test-timings-tag::tag", "operator": "=", "value": "asyncpg" },
      { "condition": "OR", "key": "stress-test-timings-tag::tag", "operator": "=", "value": "psqlpy" },
      { "condition": "OR", "key": "stress-test-timings-tag::tag", "operator": "=", "value": "psycopg" }
     ]
    }
   ]
  },
  {
   "title": "MEAN LATENCY / 10s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "stress-test-timings-tag::tag" ], "type": "tag" }
     ],
     "measurement": "stress-test-timings",
     "query": "SELECT mean(\"time-took\") FROM \"stress-test-timings\" WHERE (\"stress-test-timings-tag\"::tag = '$tag_key') AND $timeFilter GROUP BY time(10s), \"stress-test-timings-tag\"::tag",
     "select": [
      [
       { "params": [ "time-took" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "stress-test-timings-tag::tag", "operator": "=", "value": "psqlpy" },
      { "condition": "OR", "key": "stress-test-timings-tag::tag", "operator": "=", "value": "asyncpg" },
      { "condition": "OR", "key": "stress-test-timings-tag::tag", "operator": "=", "value": "psycopg" }
     ]
    }
   ]
  }
 ]
}